import ClientSelector from "./ClientSelector";
import { ClientData } from "../../types";
import { useState, useEffect, useRef, ChangeEvent } from "react";
// @ts-ignore
import html2pdf from "html2pdf.js";
import Logo from "../Logo";
import { ReportSignature } from "./ReportBranding";
import { preprocessStylesheets, restoreStylesheets, exportToWord, copyRichText } from "../../lib/pdfUtils";
import LaudoPricingTab from "./LaudoPricingTab";
import { 
  Shield, 
  FileText, 
  Wand2, 
  CheckCircle2, 
  AlertTriangle, 
  Printer, 
  FileDown, 
  Plus, 
  Trash2, 
  UserCheck, 
  Calendar, 
  MapPin, 
  Sparkles,
  Info,
  X,
  ChevronDown,
  Upload,
  Maximize2,
  Minimize2,
  Copy,
  Layers as LayersIcon,
  HelpCircle,
  Calculator
} from "lucide-react";
import {
  UploadedImage,
  PlaygroundChecklistItem,
  EquipmentClassification,
  PlaygroundNaoConformidade,
  PlaygroundPerigo,
  DEFAULT_PLAYGROUND_CHECKLIST,
  PREFILLED_PLAYGROUND_PARAMS,
  PREFILLED_PLAYGROUND_CHECKLIST,
  PREFILLED_PLAYGROUND_CLASSIFICATION,
  PREFILLED_PLAYGROUND_PERIGOS,
  PREFILLED_PLAYGROUND_NAO_CONFORMIDADES,
  DEFAULT_PLAYGROUND_SECOES
} from "./playgroundData";

interface Props {
  clients?: ClientData[];
  onBack: () => void;
  initialPrefilled?: boolean;
}

type TabType = "params" | "checklist" | "equipments" | "nonconformities" | "pricing" | "preview";

export default function LaudoPlaygroundIndep({ onBack, initialPrefilled = false, clients }: Props) {
  const [activeTab, setActiveTab] = useState<TabType>("params");
  const [fullscreen, setFullscreen] = useState(false);
  const [loadingAI, setLoadingAI] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [uploadedImages, setUploadedImages] = useState<UploadedImage[]>([]);

  // Core Parameters state
  const [laudoParams, setLaudoParams] = useState({
    laudoNumber: "LPG-101/2026 Rev. 00",
    clientName: "Condomínio Residencial Bella Vista",
    cnpj: "00.000.000/0001-00",
    address: "Endereço Operacional Completo",
    laudoDate: "04/07/2026",
    city: "Recife",
    targetAgeGroup: "02 a 12 anos",
    totalArea: "100 m²",
    numEquipments: "4",
    materialType: "Eucalipto Autoclavado, Metal Galvanizado e Plástico Rotomoldado",
    installYearEst: "2021",
    floorType: "Grama sintética sobre asfalto rígido (12mm)",
    fencingStatus: "Presente, altura de 1,10m com portão manual (sem auto-fechamento)",
    lightingStatus: "Inexistente",
    shadowStatus: "Inexistente",
    maintenanceStatus: "Não informada",
    notes: "",
    coverImage: "",
    normasAdicionais: "ABNT NBR 16071, EN 1176, ASTM F1487",
    blankSignature: false
  });

  // Print & Section options
  const [printConfig, setPrintConfig] = useState({
    capa: true,
    carta: true,
    sumario: true,
    secoes: true
  });

  // Structural lists and checklists
  const [checklist, setChecklist] = useState<PlaygroundChecklistItem[]>(DEFAULT_PLAYGROUND_CHECKLIST);
  const [classifications, setClassifications] = useState<EquipmentClassification[]>([]);
  const [perigos, setPerigos] = useState<PlaygroundPerigo[]>([]);
  const [naoConformidades, setNaoConformidades] = useState<PlaygroundNaoConformidade[]>([]);
  const [conclusao, setConclusao] = useState({
    status: "REPROVADO" as "APROVADO" | "REPROVADO" | "APROVADO COM RESTRIÇÕES",
    parecer: "Preencha a vistoria técnica e clique em simular ou gerar com IA para gerar o parecer conclusivo oficial com o carimbo do CREA."
  });

  const [secoes, setSecoes] = useState<Record<string, string>>(DEFAULT_PLAYGROUND_SECOES);
  const reportRef = useRef<HTMLDivElement>(null);

  // Initialize prefilled if requested
  useEffect(() => {
    if (initialPrefilled) {
      loadSimulatedData();
    }
  }, [initialPrefilled]);

  // Update dynamic sections locally based on manual parameters when not generated by AI
  useEffect(() => {
    if (!loadingAI && secoes["introducao"] === "Carregando introdução técnica...") {
      setSecoes({
        introducao: `O presente Laudo Técnico visa realizar a vistoria pericial e apreciação detalhada de segurança na área recreativa destinada ao lazer infantil (playground) de ${laudoParams.clientName}. A análise fundamenta-se nos preceitos legais e normativos nacionais vigentes, com ênfase absoluta na prevenção de sinistros envolvendo o público infantil, cuja integridade física exige rigorosa aplicação de engenharia de segurança preventiva.`,
        metodologia: `A metodologia adotada compreendeu a realização de vistoria visual detalhada no local, ensaios dimensionais de aberturas com gabaritos regulamentares (sondas de cabeça e pescoço conforme preconiza a NBR 16071), medição de distâncias livres de segurança entre equipamentos e inspeção mecânica dos componentes de madeira, fixação metálica e plásticos. Não foram realizados ensaios destrutivos estruturais, limitando-se a análise às condições superficiais observáveis e ensaios não destrutivos de funcionamento dinâmico normal dos brinquedos.`,
        equipamentos_analisados: `Os brinquedos inspecionados consistem em uma quantidade total de ${laudoParams.numEquipments} equipamentos instalados, confeccionados predominantemente com o material: ${laudoParams.materialType}. O playground destina-se a crianças de ${laudoParams.targetAgeGroup} em área total aproximada de ${laudoParams.totalArea}. O revestimento do piso é de ${laudoParams.floorType}.`,
        conclusao_text: `Diante de todas as não conformidades constatadas nesta perícia, classificamos o playground em questão como **${conclusao.status}** para utilização operacional em seu estado atual. A liberação de uso seguro fica estritamente vinculada à resolução total e auditoria mecânica subsequente dos pontos descritos no plano de ação.`
      });
    }
  }, [laudoParams, conclusao.status]);

  // Load beautiful, highly comprehensive real simulated data matching the specifications
  const loadSimulatedData = () => {
    setLaudoParams({
      ...PREFILLED_PLAYGROUND_PARAMS,
      coverImage: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?q=80&w=800&auto=format&fit=crop"
    });
    setChecklist(PREFILLED_PLAYGROUND_CHECKLIST);
    setClassifications(PREFILLED_PLAYGROUND_CLASSIFICATION);
    setPerigos(PREFILLED_PLAYGROUND_PERIGOS);
    setNaoConformidades(PREFILLED_PLAYGROUND_NAO_CONFORMIDADES);
    setConclusao({
      status: "REPROVADO",
      parecer: "A área de recreação infantil (playground) analisada foi classificada como REPROVADA e recomendada para INTERDIÇÃO FÍSICA INTEGRAL IMEDIATA. Constatou-se perigo crítico de asfixia por aprisionamento de cabeça na escada do Multiplay (vão de 140 mm), associado à completa falta de amortecimento do piso sob altura crítica de queda acentuada (1,60 m). A liberação técnica segura fica condicionada à execução total do plano de ação corretivo de engenharia."
    });
    
    // Generate simulated dynamic sections
    const params = PREFILLED_PLAYGROUND_PARAMS;
    setSecoes({
      introducao: `O presente Laudo Técnico visa realizar a vistoria pericial e apreciação detalhada de segurança na área recreativa destinada ao lazer infantil (playground) do condomínio ${params.clientName}. A análise fundamenta-se nos preceitos legais e normativos nacionais vigentes (ABNT NBR 16071), com ênfase absoluta na prevenção de sinistros envolvendo o público infantil, cuja integridade física exige rigorosa aplicação de engenharia de segurança preventiva.`,
      metodologia: `A metodologia adotada compreendeu a realização de vistoria visual detalhada no local, ensaios dimensionais de aberturas com gabaritos regulamentares (sondas de cabeça e pescoço conforme preconiza a NBR 16071), medição de distâncias livres de segurança entre equipamentos e inspeção mecânica dos componentes de madeira, fixação metálica e plásticos. Não foram realizados ensaios destrutivos estruturais, limitando-se a análise às condições superficiais observáveis e ensaios não destrutivos de funcionamento dinâmico normal dos brinquedos.`,
      equipamentos_analisados: `Os brinquedos inspecionados compreendem um total de ${params.numEquipments} itens, confeccionados em material ${params.materialType}. O playground destina-se a crianças de ${params.targetAgeGroup} em área total aproximada de ${params.totalArea}. O revestimento do piso é de ${params.floorType}. Os gradis de fechamento encontram-se descritos como: ${params.fencingStatus}.`,
      conclusao_text: `Diante de todas as não conformidades constatadas nesta perícia, classificamos o playground em questão como **REPROVADO** para utilização operacional em seu estado atual. A presença de fatores graves de perigo como o vão de aprisionamento de cabeça na escada do Multiplay e a total ausência de amortecimento crítico no piso (grama sintética colada diretamente sobre laje de concreto duro) geram riscos severos de asfixia mecânica e traumatismo cranioencefálico por queda livre das plataformas elevadas. Recomenda-se a INTERDIÇÃO INTEGRAL IMEDIATA do espaço recreativo, com isolamento físico por fitas zebradas e barreiras, até que o Plano de Ação seja executado de forma auditada pela VL Engenharia.`
    });
  };

  // Image upload handling with local preview
  const handleImageUpload = (e: ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files) return;
    const files = Array.from(e.target.files) as File[];
    files.forEach((file: File) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        setUploadedImages(prev => [
          ...prev,
          {
            name: file.name,
            data: reader.result as string,
            description: "Registro fotográfico visual de segurança: " + file.name.split(".")[0]
          }
        ]);
      };
      reader.readAsDataURL(file);
    });
  };

  const removeImage = (index: number) => {
    setUploadedImages(prev => prev.filter((_, i) => i !== index));
  };

  // Checklist updates
  const updateChecklistItem = (id: string, field: keyof PlaygroundChecklistItem, val: string) => {
    setChecklist(prev => prev.map(it => it.id === id ? { ...it, [field]: val } : it));
  };

  // Equipment classifications updates
  const addClassification = () => {
    const nextId = "C-" + String(classifications.length + 1).padStart(2, "0");
    setClassifications(prev => [
      ...prev,
      {
        id: nextId,
        name: "Novo Brinquedo",
        estado: "Apresenta ótimas condições de conservação...",
        condicao: "VERDE",
        acaoRecomendada: "Monitorar periodicamente"
      }
    ]);
  };

  const updateClassification = (id: string, field: keyof EquipmentClassification, val: string) => {
    setClassifications(prev => prev.map(it => it.id === id ? { ...it, [field]: val } : it));
  };

  const removeClassification = (id: string) => {
    setClassifications(prev => prev.filter(it => it.id !== id));
  };

  // Active perigos updates
  const addPerigo = () => {
    const nextId = "P-" + String(perigos.length + 1).padStart(2, "0");
    setPerigos(prev => [
      ...prev,
      {
        id: nextId,
        equipamento: "Geral",
        perigo: "Novo perigo detectado...",
        risco: "Queda ou laceração mecânica...",
        gravidade: "BAIXA"
      }
    ]);
  };

  const updatePerigo = (id: string, field: keyof PlaygroundPerigo, val: string) => {
    setPerigos(prev => prev.map(it => it.id === id ? { ...it, [field]: val } : it));
  };

  const removePerigo = (id: string) => {
    setPerigos(prev => prev.filter(it => it.id !== id));
  };

  // Non-conformities list updates
  const addNaoConformidade = () => {
    const nextId = "NC-" + String(naoConformidades.length + 1).padStart(2, "0");
    setNaoConformidades(prev => [
      ...prev,
      {
        id: nextId,
        equipamento: "Geral",
        problema: "Descrição da não conformidade...",
        norma: "ABNT NBR 16071-1 item...",
        recomendacao: "Substituir ou adequar...",
        prioridade: "MÉDIO PRAZO",
        responsavel: "Administração",
        prazo: "10 dias"
      }
    ]);
  };

  const updateNaoConformidade = (id: string, field: keyof PlaygroundNaoConformidade, val: string) => {
    setNaoConformidades(prev => prev.map(it => it.id === id ? { ...it, [field]: val } : it));
  };

  const removeNaoConformidade = (id: string) => {
    setNaoConformidades(prev => prev.filter(it => it.id !== id));
  };

  // AI-Powered mechanical audit invocation
  const handleAIAudit = async () => {
    setLoadingAI(true);
    // Mark sections loading
    setSecoes({
      introducao: "Carregando introdução técnica...",
      metodologia: "Carregando metodologia...",
      equipamentos_analisados: "Analisando equipamentos com inteligência artificial...",
      conclusao_text: "Processando parecer conclusivo do Engenheiro Vitor Leonardo..."
    });

    try {
      const response = await fetch("/api/gemini/playground-audit", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          ...laudoParams,
          notes: aiPrompt + "\n" + laudoParams.notes,
          images: uploadedImages.map(img => ({ data: img.data, mimeType: "image/jpeg" }))
        })
      });

      if (!response.ok) {
        throw new Error("Erro no servidor ao processar laudo de playground.");
      }

      const data = await response.json();

      if (data.numero) {
        setLaudoParams(prev => ({ ...prev, laudoNumber: data.numero }));
      }
      if (data.checklist) {
        setChecklist(prev => prev.map(it => {
          const resObj = data.checklist[it.id];
          if (resObj) {
            return {
              ...it,
              status: resObj.resposta === "SIM" ? "OK" : resObj.resposta === "NÃO" ? "NOK" : "N/A",
              nota: resObj.nota || it.nota
            };
          }
          return it;
        }));
      }
      if (data.classificacao_equipamentos) {
        setClassifications(data.classificacao_equipamentos);
      }
      if (data.perigos) {
        setPerigos(data.perigos);
      }
      if (data.nao_conformidades) {
        setNaoConformidades(data.nao_conformidades);
      }
      if (data.conclusao) {
        setConclusao(data.conclusao);
      }
      if (data.secoes) {
        setSecoes(data.secoes);
      }
      setActiveTab("preview");
    } catch (err) {
      console.error(err);
      alert("Houve um erro técnico ao gerar com IA. Ativando o motor de simulação fallback.");
      loadSimulatedData();
    } finally {
      setLoadingAI(false);
    }
  };

  // Export flows
  const handlePrintPDF = async () => {
    const element = reportRef.current;
    if (!element) return;

    try {
      await preprocessStylesheets(element);
      const opt = {
        margin: [10, 10, 10, 10] as [number, number, number, number],
        filename: `${laudoParams.laudoNumber.replace(/\//g, "-")}_Laudo_Playground.pdf`,
        image: { type: "jpeg" as const, quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, letterRendering: true },
        jsPDF: { unit: "mm", format: "a4" as const, orientation: "portrait" as const },
        pagebreak: { mode: ["css", "legacy"] as any }
      };

      await html2pdf().from(element).set(opt).save();
    } catch (e) {
      console.error("PDF generation failure", e);
      alert("Erro ao exportar PDF. Tente novamente.");
    } finally {
      restoreStylesheets();
    }
  };

  const handleExportWord = () => {
    exportToWord("playground-report-container", `${laudoParams.laudoNumber.replace(/\//g, "-")}_Laudo_Playground`);
  };

  const handleCopyRichText = async () => {
    const ok = await copyRichText("playground-report-container");
    if (ok) {
      alert("Laudo copiado em formato Rich Text! Pronto para colar no Google Docs ou Microsoft Word.");
    } else {
      alert("Falha ao copiar documento.");
    }
  };

  return (
    <div id="laudo-playground-root" className={`flex flex-col bg-slate-50 min-h-screen text-slate-800 ${fullscreen ? "fixed inset-0 z-50 overflow-y-auto" : ""}`}>
      {/* Top action header */}
      <div className="flex justify-between items-center bg-slate-900 border-b border-slate-800 px-6 py-4 text-white shrink-0 print:hidden">
        <div className="flex items-center gap-3">
          <div className="bg-amber-500 p-2 rounded-lg text-slate-950 font-bold">
            <Shield className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-lg font-bold font-sans tracking-tight">SISTEMA LAUDO PLAYGROUND</h1>
            <p className="text-slate-400 text-xs font-mono">VL Engenharia — NBR 16071 / Vitor Leonardo</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button 
            onClick={() => setFullscreen(!fullscreen)}
            className="hover:bg-slate-800 p-2 rounded text-slate-400 hover:text-white transition-colors"
            title="Alternar tela cheia"
          >
            {fullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
          </button>
          <button 
            onClick={onBack}
            className="bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded text-slate-300 hover:text-white text-sm font-medium transition-colors"
          >
            Voltar ao Dashboard
          </button>
        </div>
      </div>

      {/* Main layout */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left editor side */}
        <div className="flex flex-col flex-1 border-r border-slate-200 overflow-y-auto p-6 print:hidden">
          
          {/* Quick simulation banner */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div className="flex gap-3">
              <Sparkles className="w-6 h-6 text-amber-500 shrink-0 mt-0.5" />
              <div>
                <h4 className="font-semibold text-slate-900">Demonstração & Teste Rápido</h4>
                <p className="text-slate-600 text-sm">Preencha o formulário instantaneamente com um exemplo técnico real completo de inspeção de playground do Condomínio Bella Vista.</p>
              </div>
            </div>
            <button 
              onClick={loadSimulatedData}
              className="bg-amber-500 hover:bg-amber-600 active:scale-95 text-slate-950 font-semibold px-4 py-2 rounded-lg text-sm flex items-center gap-2 transition-all shrink-0 shadow-sm"
            >
              <CheckCircle2 className="w-4 h-4" />
              Simular Vistoria VL
            </button>
          </div>

          {/* AI Generator Box */}
          <div className="bg-gradient-to-r from-blue-900 to-indigo-950 rounded-xl p-5 text-white mb-6 shadow-md relative overflow-hidden">
            <div className="absolute right-0 bottom-0 text-white/5 pointer-events-none">
              <Wand2 className="w-40 h-40" />
            </div>
            <div className="relative z-10">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="w-5 h-5 text-blue-400" />
                <h3 className="font-bold font-sans tracking-tight text-base">Gerador de Laudos NBR 16071 com IA</h3>
              </div>
              <p className="text-slate-300 text-xs mb-4">
                Envie até 3 fotos do playground. A inteligência artificial identificará se há inconformidades com a norma NBR 16071, preencherá o checklist de 18 itens e estimará a criticidade pericial automaticamente.
              </p>

              {/* Image upload widget */}
              <div className="mb-4">
                <div className="flex flex-wrap gap-2 mb-2">
                  {uploadedImages.map((img, i) => (
                    <div key={i} className="relative group w-20 h-20 bg-slate-800 border border-slate-700 rounded-lg overflow-hidden">
                      <img src={img.data} alt="preview" className="w-full h-full object-cover" />
                      <button 
                        onClick={() => removeImage(i)}
                        className="absolute top-1 right-1 bg-red-600 hover:bg-red-700 text-white rounded-full p-1"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  ))}
                  {uploadedImages.length < 3 && (
                    <label className="border-2 border-dashed border-slate-700 hover:border-blue-400 w-20 h-20 rounded-lg flex flex-col justify-center items-center cursor-pointer hover:bg-slate-900/50 transition-colors">
                      <Upload className="w-4 h-4 text-slate-400" />
                      <span className="text-[10px] text-slate-400 mt-1">Upload</span>
                      <input 
                        type="file" 
                        accept="image/*" 
                        multiple 
                        onChange={handleImageUpload} 
                        className="hidden" 
                      />
                    </label>
                  )}
                </div>
                {uploadedImages.length > 0 && (
                  <p className="text-[11px] text-blue-300">{uploadedImages.length} de 3 fotos adicionadas</p>
                )}
              </div>

              <div className="flex gap-2">
                <input 
                  type="text" 
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                  placeholder="Instruções extras (ex: 'Condições críticas, brinquedos danificados, madeira lascando...')"
                  className="bg-slate-900/60 border border-slate-700 rounded-lg px-3 py-2 text-sm flex-1 text-white placeholder-slate-400 focus:outline-none focus:border-blue-500"
                />
                <button 
                  onClick={handleAIAudit}
                  disabled={loadingAI}
                  className="bg-blue-500 hover:bg-blue-600 disabled:bg-slate-700 disabled:text-slate-400 text-white font-semibold px-4 py-2 rounded-lg text-sm flex items-center gap-2 transition-all shrink-0 shadow-sm"
                >
                  <Wand2 className="w-4 h-4" />
                  {loadingAI ? "Analisando..." : "Auditar com IA"}
                </button>
              </div>
            </div>
          </div>

          {/* Tab buttons */}
          <div className="flex border-b border-slate-200 mb-6 shrink-0 bg-white rounded-lg p-1 shadow-sm">
            <button 
              onClick={() => setActiveTab("params")}
              className={`flex-1 py-2.5 text-center text-sm font-medium rounded-md transition-colors ${activeTab === "params" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:text-slate-900"}`}
            >
              1. Parâmetros
            </button>
            <button 
              onClick={() => setActiveTab("checklist")}
              className={`flex-1 py-2.5 text-center text-sm font-medium rounded-md transition-colors ${activeTab === "checklist" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:text-slate-900"}`}
            >
              2. Checklist
            </button>
            <button 
              onClick={() => setActiveTab("equipments")}
              className={`flex-1 py-2.5 text-center text-sm font-medium rounded-md transition-colors ${activeTab === "equipments" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:text-slate-900"}`}
            >
              3. Brinquedos
            </button>
            <button 
              onClick={() => setActiveTab("nonconformities")}
              className={`flex-1 py-2.5 text-center text-sm font-medium rounded-md transition-colors ${activeTab === "nonconformities" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:text-slate-900"}`}
            >
              4. Não Conformidades
            </button>
            <button 
              onClick={() => setActiveTab("pricing")}
              className={`flex-1 py-2.5 text-center text-sm font-medium rounded-md transition-colors flex items-center justify-center gap-1 ${activeTab === "pricing" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:text-slate-900"}`}
            >
              <Calculator className="w-3.5 h-3.5 text-emerald-400" />
              5. Precificação
            </button>
            <button 
              onClick={() => setActiveTab("preview")}
              className={`flex-1 py-2.5 text-center text-sm font-medium rounded-md transition-colors ${activeTab === "preview" ? "bg-slate-900 text-white shadow-sm" : "text-slate-600 hover:text-slate-900"}`}
            >
              6. Visualização
            </button>
          </div>

          {/* Form Content active tab view */}
          <div className="flex-1 bg-white border border-slate-200 rounded-xl p-6 shadow-sm">
            {activeTab === "pricing" && (
              <LaudoPricingTab 
                clientName={laudoParams.clientName}
                serviceType="Laudo de Playground"
                equipmentName={laudoParams.playgroundType || "Playground de Madeira"}
              />
            )}

            {activeTab === "params" && (
              <div className="space-y-4">
                <div className="border-b border-slate-100 pb-3 mb-2">
                  <h3 className="font-bold text-slate-950 font-sans tracking-tight text-base">Identificação e Parâmetros Locais</h3>
                  <p className="text-slate-500 text-xs">Insira os dados cadastrais da contratante e as condições físicas do playground visitado.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Número do Laudo</label>
                    <input 
                      type="text" 
                      value={laudoParams.laudoNumber}
                      onChange={(e) => setLaudoParams({ ...laudoParams, laudoNumber: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>

                  <div className="flex items-center gap-2 py-2 col-span-1 md:col-span-2">
                    <input
                      type="checkbox"
                      id="blankSignaturePlayground"
                      checked={laudoParams.blankSignature || false}
                      onChange={e => setLaudoParams({ ...laudoParams, blankSignature: e.target.checked })}
                      className="rounded border-slate-300 dark:border-slate-700 text-emerald-600 focus:ring-emerald-500"
                    />
                    <label htmlFor="blankSignaturePlayground" className="text-xs font-semibold text-slate-700 dark:text-slate-300 cursor-pointer select-none">
                      Deixar assinatura em branco (para assinar depois via Gov.br)
                    </label>
                  </div>

              {/* Seleção de Cliente Pré-cadastrado */}
              <div className="p-3.5 bg-slate-50 dark:bg-slate-950/40 border border-slate-200 dark:border-slate-800/80 rounded-xl mb-4 col-span-1 md:col-span-2">
                <ClientSelector
                  clients={clients}
                  label="Selecionar Cliente Cadastrado"
                  onSelectClient={(client) => {
                    if (client.id) {
                      setLaudoParams(prev => ({
                        ...prev,
                        clientName: client.company || client.name,
                        cnpj: client.cnpj_cpf,
                        address: client.address
                      }));
                    }
                  }}
                />
              </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Empresa / Condomínio Contratante</label>
                    <input 
                      type="text" 
                      value={laudoParams.clientName}
                      onChange={(e) => setLaudoParams({ ...laudoParams, clientName: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">CNPJ</label>
                    <input 
                      type="text" 
                      value={laudoParams.cnpj}
                      onChange={(e) => setLaudoParams({ ...laudoParams, cnpj: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Endereço Completo</label>
                    <input 
                      type="text" 
                      value={laudoParams.address}
                      onChange={(e) => setLaudoParams({ ...laudoParams, address: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Data da Vistoria</label>
                    <input 
                      type="text" 
                      value={laudoParams.laudoDate}
                      onChange={(e) => setLaudoParams({ ...laudoParams, laudoDate: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Cidade da Inspeção</label>
                    <input 
                      type="text" 
                      value={laudoParams.city}
                      onChange={(e) => setLaudoParams({ ...laudoParams, city: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Faixa Etária Recomendada</label>
                    <input 
                      type="text" 
                      value={laudoParams.targetAgeGroup}
                      onChange={(e) => setLaudoParams({ ...laudoParams, targetAgeGroup: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Área Total do Playground</label>
                    <input 
                      type="text" 
                      value={laudoParams.totalArea}
                      onChange={(e) => setLaudoParams({ ...laudoParams, totalArea: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Quantidade de Equipamentos</label>
                    <input 
                      type="text" 
                      value={laudoParams.numEquipments}
                      onChange={(e) => setLaudoParams({ ...laudoParams, numEquipments: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Material Predominante</label>
                    <input 
                      type="text" 
                      value={laudoParams.materialType}
                      onChange={(e) => setLaudoParams({ ...laudoParams, materialType: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Ano de Instalação</label>
                    <input 
                      type="text" 
                      value={laudoParams.installYearEst}
                      onChange={(e) => setLaudoParams({ ...laudoParams, installYearEst: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Tipo de Piso e Espessura</label>
                    <input 
                      type="text" 
                      value={laudoParams.floorType}
                      onChange={(e) => setLaudoParams({ ...laudoParams, floorType: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Cercamento e Gradis</label>
                    <input 
                      type="text" 
                      value={laudoParams.fencingStatus}
                      onChange={(e) => setLaudoParams({ ...laudoParams, fencingStatus: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Iluminação Artificial</label>
                    <input 
                      type="text" 
                      value={laudoParams.lightingStatus}
                      onChange={(e) => setLaudoParams({ ...laudoParams, lightingStatus: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Sombreamento</label>
                    <input 
                      type="text" 
                      value={laudoParams.shadowStatus}
                      onChange={(e) => setLaudoParams({ ...laudoParams, shadowStatus: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Histórico de Manutenção</label>
                    <input 
                      type="text" 
                      value={laudoParams.maintenanceStatus}
                      onChange={(e) => setLaudoParams({ ...laudoParams, maintenanceStatus: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    />
                  </div>
                </div>

                <div className="space-y-1">
                  <label className="block text-xs font-semibold text-slate-700 mb-1">Normas de Referência Adicionais / Internacionais</label>
                  <textarea
                    placeholder="Ex: ABNT NBR 16071, EN 1176, ASTM F1487, etc. (Separe por vírgulas)"
                    className="w-full border border-slate-300 rounded-lg p-3 text-slate-800 font-mono text-xs focus:outline-none focus:border-slate-800"
                    value={laudoParams.normasAdicionais || ""}
                    onChange={e => setLaudoParams({ ...laudoParams, normasAdicionais: e.target.value })}
                    rows={2}
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">Observações / Notas Gerais de Campo</label>
                  <textarea 
                    rows={3}
                    value={laudoParams.notes}
                    onChange={(e) => setLaudoParams({ ...laudoParams, notes: e.target.value })}
                    className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                  />
                </div>

                <div className="space-y-1 pt-4 border-t border-slate-200">
                  <label className="block text-xs font-semibold text-slate-700 mb-1">Foto de Destaque da Capa do Laudo</label>
                  <div className="flex flex-col sm:flex-row items-center gap-4 bg-slate-50 p-4 rounded-xl border border-slate-200">
                    {laudoParams.coverImage ? (
                      <div className="relative w-full sm:w-48 h-28 rounded-xl overflow-hidden border border-slate-300 shadow-sm shrink-0">
                        <img src={laudoParams.coverImage} className="w-full h-full object-cover" alt="Cover preview" referrerPolicy="no-referrer" />
                        <button
                          type="button"
                          onClick={() => setLaudoParams({ ...laudoParams, coverImage: "" })}
                          className="absolute top-1 right-1 bg-red-600 hover:bg-red-700 text-white rounded-full p-1 shadow transition-all cursor-pointer"
                        >
                          <X className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    ) : (
                      <div className="w-full sm:w-48 h-28 bg-slate-100 rounded-xl flex items-center justify-center border border-dashed border-slate-300 text-slate-400 shrink-0">
                        <FileText className="w-8 h-8" />
                      </div>
                    )}

                    <div className="flex-grow space-y-2 w-full text-center sm:text-left">
                      <p className="text-xs text-slate-500">Escolha uma foto geral ou panorâmica do playground. Esta imagem aparecerá centralizada na folha de capa do laudo técnico.</p>
                      <label className="inline-flex items-center gap-2 bg-slate-900 hover:bg-slate-800 text-white font-semibold px-4 py-2 rounded-lg text-xs cursor-pointer shadow-sm transition-all">
                        <Upload className="w-4 h-4" />
                        <span>Selecionar Imagem</span>
                        <input
                          type="file"
                          accept="image/*"
                          className="hidden"
                          onChange={e => {
                            const file = e.target.files?.[0];
                            if (file) {
                              const reader = new FileReader();
                              reader.onloadend = () => {
                                setLaudoParams(prev => ({ ...prev, coverImage: reader.result as string }));
                              };
                              reader.readAsDataURL(file);
                            }
                          }}
                        />
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {activeTab === "checklist" && (
              <div className="space-y-4">
                <div className="border-b border-slate-100 pb-3">
                  <h3 className="font-bold text-slate-950 font-sans tracking-tight text-base">Checklist Regulamentar NBR 16071</h3>
                  <p className="text-slate-500 text-xs">Avalie a presença e conformidade dos dispositivos de segurança infantil do playground.</p>
                </div>

                <div className="max-h-[500px] overflow-y-auto space-y-4 pr-2">
                  {checklist.map((it) => (
                    <div key={it.id} className="border border-slate-200 rounded-lg p-4 bg-slate-50">
                      <div className="flex flex-col md:flex-row justify-between md:items-center gap-3 mb-3">
                        <span className="text-xs font-bold text-slate-500 font-mono">{it.id.toUpperCase()} - {it.local}</span>
                        <div className="flex items-center gap-2">
                          <span className="text-xs text-slate-600 font-medium">Status:</span>
                          <select 
                            value={it.status}
                            onChange={(e) => updateChecklistItem(it.id, "status", e.target.value as any)}
                            className={`text-xs font-semibold px-2 py-1 rounded border focus:outline-none ${
                              it.status === "OK" ? "bg-emerald-50 text-emerald-700 border-emerald-300" :
                              it.status === "NOK" ? "bg-red-50 text-red-700 border-red-300" : "bg-slate-100 text-slate-600 border-slate-300"
                            }`}
                          >
                            <option value="OK">CONFORME (OK)</option>
                            <option value="NOK">NÃO CONFORME (NOK)</option>
                            <option value="N/A">NÃO APLICÁVEL (N/A)</option>
                          </select>
                        </div>
                      </div>
                      <p className="text-sm font-semibold text-slate-900 mb-2">{it.item}</p>
                      <div>
                        <label className="block text-[11px] font-semibold text-slate-500 mb-1">Nota Técnica / Observação Pericial</label>
                        <input 
                          type="text" 
                          value={it.nota}
                          onChange={(e) => updateChecklistItem(it.id, "nota", e.target.value)}
                          className="w-full border border-slate-300 rounded-lg px-3 py-1.5 text-xs bg-white focus:outline-none focus:border-slate-800"
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === "equipments" && (
              <div className="space-y-6">
                {/* Section classifications */}
                <div>
                  <div className="flex justify-between items-center border-b border-slate-100 pb-3 mb-4">
                    <div>
                      <h3 className="font-bold text-slate-950 font-sans tracking-tight text-base">Classificação Individual de Equipamentos</h3>
                      <p className="text-slate-500 text-xs font-sans">Especifique a integridade física de cada brinquedo vistoriado.</p>
                    </div>
                    <button 
                      onClick={addClassification}
                      className="bg-slate-900 hover:bg-slate-800 text-white font-medium px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5 transition-colors"
                    >
                      <Plus className="w-3.5 h-3.5" /> Adicionar
                    </button>
                  </div>

                  <div className="space-y-4 max-h-[300px] overflow-y-auto pr-2">
                    {classifications.length === 0 ? (
                      <p className="text-xs text-slate-500 italic text-center py-4">Nenhum brinquedo classificado.</p>
                    ) : (
                      classifications.map((cl) => (
                        <div key={cl.id} className="border border-slate-200 rounded-lg p-4 bg-slate-50 relative">
                          <button 
                            onClick={() => removeClassification(cl.id)}
                            className="absolute top-3 right-3 text-red-500 hover:text-red-700"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                          
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
                            <div>
                              <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Nome do Equipamento / Brinquedo</label>
                              <input 
                                type="text" 
                                value={cl.name}
                                onChange={(e) => updateClassification(cl.id, "name", e.target.value)}
                                className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                              />
                            </div>
                            <div>
                              <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Condição Operacional</label>
                              <select 
                                value={cl.condicao}
                                onChange={(e) => updateClassification(cl.id, "condicao", e.target.value as any)}
                                className={`w-full border rounded-md px-2 py-1 text-xs font-semibold focus:outline-none ${
                                  cl.condicao === "VERDE" ? "bg-emerald-50 text-emerald-700 border-emerald-300" :
                                  cl.condicao === "AMARELO" ? "bg-yellow-50 text-yellow-700 border-yellow-300" :
                                  cl.condicao === "LARANJA" ? "bg-orange-50 text-orange-700 border-orange-300" :
                                  "bg-red-50 text-red-700 border-red-300"
                                }`}
                              >
                                <option value="VERDE">VERDE (Ótimo / Seguro)</option>
                                <option value="AMARELO">AMARELO (Alerta / Monitorar)</option>
                                <option value="LARANJA">LARANJA (Crítico / Ajustar)</option>
                                <option value="VERMELHO">VERMELHO (Interditar Imediatamente)</option>
                              </select>
                            </div>
                          </div>

                          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                            <div>
                              <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Diagnóstico Técnico de Estado</label>
                              <input 
                                type="text" 
                                value={cl.estado}
                                onChange={(e) => updateClassification(cl.id, "estado", e.target.value)}
                                className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                              />
                            </div>
                            <div>
                              <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Ação Corretiva de Engenharia</label>
                              <input 
                                type="text" 
                                value={cl.acaoRecomendada}
                                onChange={(e) => updateClassification(cl.id, "acaoRecomendada", e.target.value)}
                                className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                              />
                            </div>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>

                {/* Section Active Hazards */}
                <div>
                  <div className="flex justify-between items-center border-b border-slate-100 pb-3 mb-4">
                    <div>
                      <h4 className="font-bold text-slate-950 font-sans tracking-tight text-sm">Planilha de Riscos & Perigos Críticos</h4>
                      <p className="text-slate-500 text-xs font-sans">Liste os perigos identificados no playground para elaboração da planilha pericial.</p>
                    </div>
                    <button 
                      onClick={addPerigo}
                      className="bg-slate-900 hover:bg-slate-800 text-white font-medium px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5 transition-colors"
                    >
                      <Plus className="w-3.5 h-3.5" /> Adicionar
                    </button>
                  </div>

                  <div className="space-y-4 max-h-[250px] overflow-y-auto pr-2">
                    {perigos.length === 0 ? (
                      <p className="text-xs text-slate-500 italic text-center py-4">Nenhum perigo registrado.</p>
                    ) : (
                      perigos.map((pe) => (
                        <div key={pe.id} className="border border-slate-200 rounded-lg p-4 bg-slate-50 relative">
                          <button 
                            onClick={() => removePerigo(pe.id)}
                            className="absolute top-3 right-3 text-red-500 hover:text-red-700"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                          
                          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-3">
                            <div>
                              <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Equipamento</label>
                              <input 
                                type="text" 
                                value={pe.equipamento}
                                onChange={(e) => updatePerigo(pe.id, "equipamento", e.target.value)}
                                className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                              />
                            </div>
                            <div>
                              <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">O Perigo Detectado</label>
                              <input 
                                type="text" 
                                value={pe.perigo}
                                onChange={(e) => updatePerigo(pe.id, "perigo", e.target.value)}
                                className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                              />
                            </div>
                            <div>
                              <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Gravidade</label>
                              <select 
                                value={pe.gravidade}
                                onChange={(e) => updatePerigo(pe.id, "gravidade", e.target.value as any)}
                                className="w-full border rounded-md px-2 py-1 text-xs font-semibold focus:outline-none"
                              >
                                <option value="ALTA">ALTA</option>
                                <option value="MÉDIA">MÉDIA</option>
                                <option value="BAIXA">BAIXA</option>
                              </select>
                            </div>
                          </div>

                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Risco Associado / Consequência Física</label>
                            <input 
                              type="text" 
                              value={pe.risco}
                              onChange={(e) => updatePerigo(pe.id, "risco", e.target.value)}
                              className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                            />
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              </div>
            )}

            {activeTab === "nonconformities" && (
              <div className="space-y-4">
                <div className="flex justify-between items-center border-b border-slate-100 pb-3">
                  <div>
                    <h3 className="font-bold text-slate-950 font-sans tracking-tight text-base">Planilha de Não Conformidades & Ação Corretiva</h3>
                    <p className="text-slate-500 text-xs">Mapeie as infrações específicas detectadas perante a norma ABNT NBR 16071.</p>
                  </div>
                  <button 
                    onClick={addNaoConformidade}
                    className="bg-slate-900 hover:bg-slate-800 text-white font-medium px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5 transition-colors"
                  >
                    <Plus className="w-3.5 h-3.5" /> Adicionar Item
                  </button>
                </div>

                <div className="space-y-4 max-h-[450px] overflow-y-auto pr-2">
                  {naoConformidades.length === 0 ? (
                    <p className="text-xs text-slate-500 italic text-center py-8">Nenhuma não conformidade cadastrada no momento.</p>
                  ) : (
                    naoConformidades.map((nc) => (
                      <div key={nc.id} className="border border-slate-200 rounded-lg p-4 bg-slate-50 relative">
                        <button 
                          onClick={() => removeNaoConformidade(nc.id)}
                          className="absolute top-4 right-4 text-red-500 hover:text-red-700"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-3">
                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Equipamento</label>
                            <input 
                              type="text" 
                              value={nc.equipamento}
                              onChange={(e) => updateNaoConformidade(nc.id, "equipamento", e.target.value)}
                              className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                            />
                          </div>
                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Dispositivo da Norma Violada</label>
                            <input 
                              type="text" 
                              value={nc.norma}
                              onChange={(e) => updateNaoConformidade(nc.id, "norma", e.target.value)}
                              className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                            />
                          </div>
                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Prioridade da Intervenção</label>
                            <select 
                              value={nc.prioridade}
                              onChange={(e) => updateNaoConformidade(nc.id, "prioridade", e.target.value as any)}
                              className="w-full border rounded-md px-2 py-1 text-xs font-semibold focus:outline-none"
                            >
                              <option value="IMEDIATO">IMEDIATO</option>
                              <option value="CURTO PRAZO">CURTO PRAZO</option>
                              <option value="MÉDIO PRAZO">MÉDIO PRAZO</option>
                              <option value="LONGO PRAZO">LONGO PRAZO</option>
                            </select>
                          </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Problema Detalhado</label>
                            <input 
                              type="text" 
                              value={nc.problema}
                              onChange={(e) => updateNaoConformidade(nc.id, "problema", e.target.value)}
                              className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                            />
                          </div>
                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Recomendação Técnica</label>
                            <input 
                              type="text" 
                              value={nc.recomendacao}
                              onChange={(e) => updateNaoConformidade(nc.id, "recomendacao", e.target.value)}
                              className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                            />
                          </div>
                        </div>

                        <div className="grid grid-cols-2 gap-3">
                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Responsável pela Execução</label>
                            <input 
                              type="text" 
                              value={nc.responsavel}
                              onChange={(e) => updateNaoConformidade(nc.id, "responsavel", e.target.value)}
                              className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                            />
                          </div>
                          <div>
                            <label className="block text-[10px] font-semibold text-slate-600 mb-0.5">Prazo Sugerido</label>
                            <input 
                              type="text" 
                              value={nc.prazo}
                              onChange={(e) => updateNaoConformidade(nc.id, "prazo", e.target.value)}
                              className="w-full border border-slate-300 rounded-md px-2 py-1 text-xs focus:outline-none"
                            />
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>

                <div className="border-t border-slate-100 pt-4 mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Status Final do Laudo</label>
                    <select 
                      value={conclusao.status}
                      onChange={(e) => setConclusao({ ...conclusao, status: e.target.value as any })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-slate-800"
                    >
                      <option value="REPROVADO">REPROVADO / INTERDITADO</option>
                      <option value="APROVADO">APROVADO (Totalmente Seguro)</option>
                      <option value="APROVADO COM RESTRIÇÕES">APROVADO COM RESTRIÇÕES</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">Parecer Conclusivo Final (CREA)</label>
                    <textarea 
                      rows={2}
                      value={conclusao.parecer}
                      onChange={(e) => setConclusao({ ...conclusao, parecer: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-1 text-xs focus:outline-none focus:border-slate-800"
                    />
                  </div>
                </div>
              </div>
            )}

            {activeTab === "preview" && (
              <div className="space-y-4">
                <div className="border-b border-slate-100 pb-3 mb-2 flex justify-between items-center">
                  <div>
                    <h3 className="font-bold text-slate-950 font-sans tracking-tight text-base">Revisão de Textos Técnicos</h3>
                    <p className="text-slate-500 text-xs">Visualize e edite as seções narrativas textuais do laudo antes de exportar.</p>
                  </div>
                </div>

                <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Seção 1: Introdução & Objetivos</label>
                    <textarea 
                      rows={4}
                      value={secoes["introducao"] || ""}
                      onChange={(e) => setSecoes({ ...secoes, introducao: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Seção 2: Metodologia de Inspeção</label>
                    <textarea 
                      rows={4}
                      value={secoes["metodologia"] || ""}
                      onChange={(e) => setSecoes({ ...secoes, metodologia: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Seção 3: Equipamentos e Entorno</label>
                    <textarea 
                      rows={4}
                      value={secoes["equipamentos_analisados"] || ""}
                      onChange={(e) => setSecoes({ ...secoes, equipamentos_analisados: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Seção 4: Considerações de Encerramento</label>
                    <textarea 
                      rows={4}
                      value={secoes["conclusao_text"] || ""}
                      onChange={(e) => setSecoes({ ...secoes, conclusao_text: e.target.value })}
                      className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none"
                    />
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right Preview Side */}
        <div className="flex-1 bg-slate-200 overflow-y-auto p-6 flex flex-col items-center">
          {/* Action floating buttons */}
          <div className="flex flex-wrap gap-2 mb-4 shrink-0 bg-white p-2 rounded-lg shadow-sm border border-slate-300 w-full max-w-[800px] justify-between">
            <span className="text-xs font-bold text-slate-600 px-2 py-2 flex items-center gap-1.5"><FileText className="w-4 h-4 text-slate-500" /> Pré-visualização do PDF</span>
            <div className="flex gap-1.5">
              <button 
                onClick={handleCopyRichText}
                className="bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-semibold px-3 py-1.5 rounded text-xs flex items-center gap-1.5 transition-colors"
                title="Copiar formatado para colar direto no Google Docs ou Word"
              >
                <Copy className="w-3.5 h-3.5 text-slate-500" /> Copiar RTF
              </button>
              <button 
                onClick={handleExportWord}
                className="bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-semibold px-3 py-1.5 rounded text-xs flex items-center gap-1.5 transition-colors"
              >
                <FileDown className="w-3.5 h-3.5 text-blue-500" /> Baixar Word (.doc)
              </button>
              <button 
                onClick={handlePrintPDF}
                className="bg-slate-900 hover:bg-slate-800 text-white font-semibold px-3 py-1.5 rounded text-xs flex items-center gap-1.5 transition-colors shadow-sm"
              >
                <Printer className="w-3.5 h-3.5 text-slate-300" /> Imprimir / PDF
              </button>
            </div>
          </div>

          {/* CONFIGURAÇÃO DE SEÇÕES DO RELATÓRIO */}
          <div className="w-full max-w-[800px] mb-4 bg-white border border-slate-300 p-4 rounded-lg print:hidden text-left shadow-sm">
            <h3 className="font-mono font-black text-[#0B2545] uppercase tracking-wider text-xs mb-2 flex items-center gap-2">
              <LayersIcon className="w-4 h-4 text-emerald-500" />
              <span>Opções de Visualização e Impressão (Configurar A4)</span>
            </h3>
            <p className="text-[11px] text-slate-500 mb-3 leading-relaxed">
              O laudo é exportado no formato A4 em alta definição. Selecione quais seções deseja incluir no documento final para padronizar com capa, sumário e apresentação.
            </p>
            
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-3 rounded-lg border border-slate-200">
              <label className="flex items-center gap-2 text-xs text-slate-700 font-medium cursor-pointer hover:text-slate-950 select-none">
                <input
                  type="checkbox"
                  checked={printConfig.capa}
                  onChange={(e) => setPrintConfig({ ...printConfig, capa: e.target.checked })}
                  className="rounded text-[#134074] focus:ring-[#134074] border-slate-300 w-4 h-4 cursor-pointer"
                />
                <span>Capa do Laudo</span>
              </label>
              <label className="flex items-center gap-2 text-xs text-slate-700 font-medium cursor-pointer hover:text-slate-950 select-none">
                <input
                  type="checkbox"
                  checked={printConfig.carta}
                  onChange={(e) => setPrintConfig({ ...printConfig, carta: e.target.checked })}
                  className="rounded text-[#134074] focus:ring-[#134074] border-slate-300 w-4 h-4 cursor-pointer"
                />
                <span>Carta de Apres.</span>
              </label>
              <label className="flex items-center gap-2 text-xs text-slate-700 font-medium cursor-pointer hover:text-slate-950 select-none">
                <input
                  type="checkbox"
                  checked={printConfig.sumario}
                  onChange={(e) => setPrintConfig({ ...printConfig, sumario: e.target.checked })}
                  className="rounded text-[#134074] focus:ring-[#134074] border-slate-300 w-4 h-4 cursor-pointer"
                />
                <span>Sumário Geral</span>
              </label>
              <label className="flex items-center gap-2 text-xs text-slate-700 font-medium cursor-pointer hover:text-slate-950 select-none">
                <input
                  type="checkbox"
                  checked={printConfig.secoes}
                  onChange={(e) => setPrintConfig({ ...printConfig, secoes: e.target.checked })}
                  className="rounded text-[#134074] focus:ring-[#134074] border-slate-300 w-4 h-4 cursor-pointer"
                />
                <span>Seções de Conteúdo</span>
              </label>
            </div>
          </div>

          {/* Clean document canvas wrapper */}
          <div 
            id="playground-report-container"
            ref={reportRef}
            className="bg-white w-full max-w-[800px] shadow-lg rounded-none border border-slate-300 p-[20mm] font-sans text-slate-900 leading-relaxed min-h-[1100px] relative overflow-hidden"
            style={{ fontFamily: "'Inter', sans-serif" }}
          >
            {/* 1. Capa do Laudo */}
            {printConfig.capa && (
              <div className="flex flex-col justify-between text-center border-b pb-8 print:border-b-0 print:pb-0 min-h-[920px] mb-8" style={{ pageBreakAfter: "always" }}>
                <div className="flex flex-col sm:flex-row justify-between items-center border-b-2 border-slate-900 pb-6 gap-4">
                  <Logo variant="print" className="h-14" />
                  <div className="text-right text-xs font-mono text-slate-400">
                    <p>Laudo Técnico de Segurança de Playground</p>
                    <p className="font-bold text-slate-800 pt-0.5">{laudoParams.laudoNumber}</p>
                  </div>
                </div>

                <div className="my-auto py-8 space-y-6">
                  <span className="text-[10px] font-mono tracking-widest text-emerald-600 dark:text-emerald-400 uppercase font-black bg-slate-100 px-4 py-1.5 rounded-full">LAUDO TÉCNICO ESPECIALIZADO DE CONFORMIDADE</span>
                  
                  <h1 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight font-sans py-2 leading-tight">
                    INSPEÇÃO E CONFORMIDADE DE SEGURANÇA EM PLAYGROUND
                  </h1>
                  <p className="text-slate-600 text-xs font-mono max-w-lg mx-auto uppercase">
                    DIAGNÓSTICO TÉCNICO E PLANO DE AÇÃO EM ÁREAS DE RECREAÇÃO INFANTIL (ABNT NBR 16071)
                  </p>

                  {/* Cover Image */}
                  <div className="my-4 max-w-xl mx-auto w-full h-64 bg-slate-50 border rounded-2xl overflow-hidden shadow-sm flex items-center justify-center relative print:border print:shadow-none print:my-2">
                    {laudoParams.coverImage ? (
                      <img src={laudoParams.coverImage} className="w-full h-full object-cover" alt="Playground Vistoriado" referrerPolicy="no-referrer" />
                    ) : (
                      <div className="text-center p-6 space-y-2 text-slate-300">
                        <p className="text-xs font-mono font-bold uppercase tracking-wider">Foto de Destaque do Playground</p>
                        <p className="text-[10px] font-sans max-w-xs mx-auto text-slate-400">Nenhuma imagem carregada para a capa. Escolha uma imagem no painel de parâmetros para ilustrar o laudo.</p>
                      </div>
                    )}
                  </div>

                  <div className="max-w-lg mx-auto bg-slate-50/50 border rounded-2xl p-5 space-y-2.5 text-left text-xs font-medium border-slate-200">
                    <p><strong>CLIENTE / CONDOMÍNIO:</strong> <span className="uppercase font-bold text-slate-800">{laudoParams.clientName}</span></p>
                    <p><strong>ENDEREÇO OPERACIONAL:</strong> {laudoParams.address}</p>
                    <p><strong>FAIXA ETÁRIA ALVO:</strong> {laudoParams.targetAgeGroup} | <strong>ÁREA TOTAL:</strong> {laudoParams.totalArea}</p>
                    <p><strong>NÚMERO DE BRINQUEDOS:</strong> <span className="font-mono text-slate-900 font-bold">{laudoParams.numEquipments}</span></p>
                    <p><strong>STATUS DE LIBERAÇÃO:</strong> <span className={`font-black uppercase ${conclusao.status === "APROVADO" ? "text-emerald-600" : "text-rose-600"}`}>{conclusao.status}</span></p>
                  </div>
                </div>

                <div className="border-t pt-6 text-xs font-mono text-slate-500 flex flex-col sm:flex-row justify-between items-center gap-4">
                  <p>VL ENGENHARIA • Eng. Vitor Leonardo CREA-PE 1822299490</p>
                  <p className="font-bold">{laudoParams.city}, {laudoParams.laudoDate}</p>
                </div>
              </div>
            )}

            {/* 2. Carta de Apresentação */}
            {printConfig.carta && (
              <div className="py-8 border-b space-y-6 min-h-[920px] flex flex-col justify-between" style={{ pageBreakAfter: "always" }}>
                <div className="space-y-6">
                  <div className="flex justify-between items-center border-b pb-4">
                    <Logo variant="print" className="h-10" />
                    <span className="text-xs font-mono text-slate-400">{laudoParams.laudoNumber}</span>
                  </div>
                  <h2 className="text-lg font-bold font-mono uppercase text-slate-900 border-b pb-1.5 pt-4">Carta de Apresentação</h2>
                  <p className="text-xs text-slate-600 font-mono text-right">{laudoParams.city}, {laudoParams.laudoDate}</p>
                  
                  <div className="space-y-4 text-xs text-slate-700 leading-relaxed font-sans font-medium text-justify">
                    <p>À Direção Técnica de <strong>{laudoParams.clientName}</strong>,</p>
                    <p>
                      Temos a satisfação de submeter à vossa apreciação técnica o Relatório Pericial Completo de Inspeção e Conformidade de Segurança correspondente à área de recreação infantil (playground) instalada em vossa unidade, vistoriada in loco por nosso engenheiro mecânico em conformidade com as diretrizes normativas vigentes.
                    </p>
                    <p>
                      Este diagnóstico técnico contempla a avaliação sistemática de integridade física dos brinquedos, medições dimensionais de vãos livres e sondagens com gabaritos regulamentares para identificação de riscos de aprisionamento de cabeça, pescoço ou dedos, bem como a avaliação das condições gerais do piso amortecedor e entorno, seguindo estritamente os preceitos da norma técnica nacional <strong>ABNT NBR 16071:2021</strong> (Partes 1 a 7).
                    </p>
                    <p>
                      Dada a gravidade dos sinistros que podem decorrer de brinquedos não conformes, elaboramos um plano de ação prioritário com cronogramas técnicos sugeridos para adequação das inconformidades reportadas. Recomendamos que as intervenções sejam executadas de forma urgente visando resguardar a vida e a integridade de todas as crianças usuárias deste espaço de lazer.
                    </p>
                    <p>
                      Colocamo-nos à inteira disposição para quaisquer esclarecimentos, suporte técnico especializado e posterior auditoria de homologação mecânica.
                    </p>
                  </div>
                </div>
                
                <div className="pt-8 text-center sm:text-left space-y-1.5 font-mono border-t border-slate-100">
                  <p className="font-bold text-slate-900 text-xs">Eng. Mecânico Vitor Leonardo Cordeiro Linhares</p>
                  <p className="text-[10px] text-slate-500">Responsável Técnico • CREA-PE 1822299490</p>
                  <p className="text-[10px] text-slate-400">VL Engenharia Diagnóstica • vitorleonardocl@gmail.com</p>
                </div>
              </div>
            )}

            {/* 3. Sumário Geral */}
            {printConfig.sumario && (
              <div className="py-8 border-b space-y-6 min-h-[920px] flex flex-col justify-between" style={{ pageBreakAfter: "always" }}>
                <div>
                  <div className="flex justify-between items-center border-b pb-4">
                    <Logo variant="print" className="h-10" />
                    <span className="text-xs font-mono text-slate-400">{laudoParams.laudoNumber}</span>
                  </div>
                  <h2 className="text-lg font-bold font-mono uppercase text-slate-900 border-b pb-1.5 pt-4">Sumário Geral do Documento</h2>
                  
                  <div className="space-y-4 font-mono text-xs text-slate-600 font-medium pt-8">
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>1. DADOS CADASTRAIS DO CLIENTE E DO PLAYGROUND</span><span>03</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>2. INTRODUÇÃO E OBJETIVOS TÉCNICOS</span><span>03</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>3. METODOLOGIA PERICIAL DE VISTORIA</span><span>03</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>4. AUDITORIA SISTEMÁTICA DO CHECKLIST (ABNT NBR 16071)</span><span>04</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>5. CLASSIFICAÇÃO TÉCNICA E ESTADO DOS BRINQUEDOS</span><span>05</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>6. MATRIZ DE RISCOS & PERIGOS IDENTIFICADOS</span><span>05</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>7. NÃO CONFORMIDADES E PLANILHA DE AÇÃO CORRETIVA</span><span>06</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>8. CONCLUSÃO TÉCNICA E PARECER PERICIAL</span><span>07</span></div>
                    <div className="flex justify-between border-b border-dashed pb-1.5"><span>ASSINATURA DO ENGENHEIRO RESPONSÁVEL</span><span>07</span></div>
                  </div>
                </div>
                
                <div className="text-center font-mono text-[9px] text-slate-400">
                  VL Engenharia Diagnóstica • Relatório Técnico de Segurança em Áreas de Lazer Infantil
                </div>
              </div>
            )}

            {/* Seções de Conteúdo */}
            {printConfig.secoes && (
              <>
                {/* Report Header */}
                {!printConfig.capa && (
                  <div className="flex justify-between items-start border-b-2 border-slate-900 pb-4 mb-6">
                    <div className="flex items-center gap-3">
                      <Logo variant="print" className="h-12" />
                      <div className="border-l border-slate-300 pl-3">
                        <h2 className="text-lg font-bold text-slate-950 tracking-tight leading-tight">VL Engenharia</h2>
                        <p className="text-[10px] text-slate-500 font-mono">ENGENHARIA DIAGNÓSTICA & SEGURANÇA</p>
                      </div>
                    </div>
                    <div className="text-right font-mono text-[10px] text-slate-500">
                      <p className="font-bold text-slate-900">LAUDO TÉCNICO DE INSPEÇÃO</p>
                      <p>{laudoParams.laudoNumber}</p>
                      <p>{laudoParams.laudoDate}</p>
                    </div>
                  </div>
                )}

                {/* Document Title */}
                {!printConfig.capa && (
                  <div className="text-center mb-8">
                    <h1 className="text-xl font-bold text-slate-950 font-sans tracking-tight leading-tight border-b border-slate-100 pb-2">
                      LAUDO TÉCNICO DE INSPEÇÃO E CONFORMIDADE DE SEGURANÇA
                    </h1>
                    <p className="text-slate-600 text-[11px] font-mono mt-1">ÁREAS DE RECREAÇÃO INFANTIL — PLAYGROUND (ABNT NBR 16071)</p>
                  </div>
                )}

                {/* Block 1: Identificação */}
                <div className="mb-6">
                  <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-3">
                    1. DADOS CADASTRAIS DO CLIENTE E DO PLAYGROUND
                  </h3>
              <table className="w-full text-xs border-collapse">
                <tbody>
                  <tr className="border-b border-slate-200">
                    <td className="py-2 font-semibold text-slate-600 w-1/3">Condomínio / Proprietário:</td>
                    <td className="py-2 text-slate-900 font-medium">{laudoParams.clientName}</td>
                  </tr>
                  <tr className="border-b border-slate-200">
                    <td className="py-2 font-semibold text-slate-600">CNPJ:</td>
                    <td className="py-2 text-slate-900 font-mono">{laudoParams.cnpj}</td>
                  </tr>
                  <tr className="border-b border-slate-200">
                    <td className="py-2 font-semibold text-slate-600">Endereço de Operação:</td>
                    <td className="py-2 text-slate-900">{laudoParams.address}</td>
                  </tr>
                  <tr className="border-b border-slate-200">
                    <td className="py-2 font-semibold text-slate-600">Data de Emissão do Laudo:</td>
                    <td className="py-2 text-slate-900 font-medium">{laudoParams.laudoDate} ({laudoParams.city})</td>
                  </tr>
                  <tr className="border-b border-slate-200">
                    <td className="py-2 font-semibold text-slate-600">Faixa Etária Recomendada:</td>
                    <td className="py-2 text-slate-900">{laudoParams.targetAgeGroup}</td>
                  </tr>
                  <tr className="border-b border-slate-200">
                    <td className="py-2 font-semibold text-slate-600">Material e Ano Estimado:</td>
                    <td className="py-2 text-slate-900">{laudoParams.materialType} / {laudoParams.installYearEst}</td>
                  </tr>
                  <tr className="border-b border-slate-200">
                    <td className="py-2 font-semibold text-slate-600">Tipo de Piso e Absorção:</td>
                    <td className="py-2 text-slate-900">{laudoParams.floorType}</td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Block 2: Introdução */}
            <div className="mb-6 page-break-before">
              <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-2">
                2. INTRODUÇÃO E OBJETIVOS TÉCNICOS
              </h3>
              <p className="text-xs text-slate-700 leading-relaxed text-justify">
                {secoes["introducao"]}
              </p>
            </div>

            {/* Block 3: Metodologia */}
            <div className="mb-6">
              <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-2">
                3. METODOLOGIA PERICIAL DE VISTORIA
              </h3>
              <p className="text-xs text-slate-700 leading-relaxed text-justify mb-2">
                {secoes["metodologia"]}
              </p>
              <p className="text-xs text-slate-700 leading-relaxed text-justify">
                {secoes["equipamentos_analisados"]}
              </p>
            </div>

            {/* Block 4: Checklist NBR 16071 */}
            <div className="mb-6 page-break-before">
              <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-3">
                4. AUDITORIA SISTEMÁTICA DO CHECKLIST (ABNT NBR 16071)
              </h3>
              <table className="w-full text-[10px] border border-slate-200 border-collapse">
                <thead>
                  <tr className="bg-slate-100 text-slate-900">
                    <th className="border border-slate-200 p-2 text-left w-12 font-mono">ID</th>
                    <th className="border border-slate-200 p-2 text-left">Requisito de Segurança</th>
                    <th className="border border-slate-200 p-2 text-center w-24">Avaliação</th>
                    <th className="border border-slate-200 p-2 text-left">Nota Observativa de Campo</th>
                  </tr>
                </thead>
                <tbody>
                  {checklist.map((it) => (
                    <tr key={it.id} className="border-b border-slate-200 hover:bg-slate-50/50">
                      <td className="border border-slate-200 p-2 font-mono font-bold text-slate-500">{it.id.toUpperCase()}</td>
                      <td className="border border-slate-200 p-2 font-medium text-slate-950">{it.item}</td>
                      <td className="border border-slate-200 p-2 text-center">
                        <span className={`px-2 py-0.5 rounded-full text-[9px] font-bold ${
                          it.status === "OK" ? "bg-emerald-100 text-emerald-800" :
                          it.status === "NOK" ? "bg-red-100 text-red-800" : "bg-slate-100 text-slate-600"
                        }`}>
                          {it.status === "OK" ? "CONFORME" : it.status === "NOK" ? "NÃO CONF." : "NÃO APLIC."}
                        </span>
                      </td>
                      <td className="border border-slate-200 p-2 text-slate-600 leading-tight">{it.nota}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Block 5: Equipments and condition */}
            {classifications.length > 0 && (
              <div className="mb-6 page-break-before">
                <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-3">
                  5. CLASSIFICAÇÃO TÉCNICA E ESTADO DOS BRINQUEDOS
                </h3>
                <table className="w-full text-[10px] border border-slate-200 border-collapse">
                  <thead>
                    <tr className="bg-slate-100 text-slate-900">
                      <th className="border border-slate-200 p-2 text-left w-12 font-mono">ID</th>
                      <th className="border border-slate-200 p-2 text-left w-1/3">Brinquedo / Equipamento</th>
                      <th className="border border-slate-200 p-2 text-left">Diagnóstico de Estado</th>
                      <th className="border border-slate-200 p-2 text-center w-24">Condição</th>
                    </tr>
                  </thead>
                  <tbody>
                    {classifications.map((cl) => (
                      <tr key={cl.id} className="border-b border-slate-200">
                        <td className="border border-slate-200 p-2 font-mono font-bold text-slate-500">{cl.id}</td>
                        <td className="border border-slate-200 p-2 font-semibold text-slate-950">{cl.name}</td>
                        <td className="border border-slate-200 p-2 text-slate-600">
                          {cl.estado} <br />
                          <span className="text-slate-900 font-medium">Recomendação: {cl.acaoRecomendada}</span>
                        </td>
                        <td className="border border-slate-200 p-2 text-center">
                          <span className={`px-2 py-0.5 rounded text-[8px] font-bold ${
                            cl.condicao === "VERDE" ? "bg-emerald-100 text-emerald-800" :
                            cl.condicao === "AMARELO" ? "bg-yellow-100 text-yellow-800" :
                            cl.condicao === "LARANJA" ? "bg-orange-100 text-orange-800" :
                            "bg-red-100 text-red-800"
                          }`}>
                            {cl.condicao}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Block 6: Hazards list */}
            {perigos.length > 0 && (
              <div className="mb-6">
                <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-3">
                  6. MATRIZ DE RISCOS & PERIGOS IDENTIFICADOS
                </h3>
                <table className="w-full text-[10px] border border-slate-200 border-collapse">
                  <thead>
                    <tr className="bg-slate-100 text-slate-900">
                      <th className="border border-slate-200 p-2 text-left w-12 font-mono">ID</th>
                      <th className="border border-slate-200 p-2 text-left w-1/4">Equipamento</th>
                      <th className="border border-slate-200 p-2 text-left">Perigo de Campo</th>
                      <th className="border border-slate-200 p-2 text-left">Consequência Física / Risco</th>
                      <th className="border border-slate-200 p-2 text-center w-20">Gravidade</th>
                    </tr>
                  </thead>
                  <tbody>
                    {perigos.map((pe) => (
                      <tr key={pe.id} className="border-b border-slate-200">
                        <td className="border border-slate-200 p-2 font-mono font-bold text-slate-500">{pe.id}</td>
                        <td className="border border-slate-200 p-2 font-semibold text-slate-900">{pe.equipamento}</td>
                        <td className="border border-slate-200 p-2 text-slate-600">{pe.perigo}</td>
                        <td className="border border-slate-200 p-2 text-slate-600">{pe.risco}</td>
                        <td className="border border-slate-200 p-2 text-center">
                          <span className={`px-2 py-0.5 rounded text-[8px] font-bold ${
                            pe.gravidade === "ALTA" ? "bg-red-100 text-red-800" :
                            pe.gravidade === "MÉDIA" ? "bg-orange-100 text-orange-800" :
                            "bg-slate-100 text-slate-700"
                          }`}>
                            {pe.gravidade}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Block 7: Non-conformities */}
            {naoConformidades.length > 0 && (
              <div className="mb-6 page-break-before">
                <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-3">
                  7. NÃO CONFORMIDADES E PLANILHA DE AÇÃO CORRETIVA
                </h3>
                <table className="w-full text-[9px] border border-slate-200 border-collapse">
                  <thead>
                    <tr className="bg-slate-100 text-slate-900">
                      <th className="border border-slate-200 p-1.5 text-left w-12 font-mono">ID</th>
                      <th className="border border-slate-200 p-1.5 text-left w-1/4">Equipamento / Norma</th>
                      <th className="border border-slate-200 p-1.5 text-left">Descrição do Desvio & Ação Recomendada</th>
                      <th className="border border-slate-200 p-1.5 text-center w-16">Urgência</th>
                      <th className="border border-slate-200 p-1.5 text-center w-16">Prazo</th>
                    </tr>
                  </thead>
                  <tbody>
                    {naoConformidades.map((nc) => (
                      <tr key={nc.id} className="border-b border-slate-200">
                        <td className="border border-slate-200 p-1.5 font-mono font-bold text-slate-500">{nc.id}</td>
                        <td className="border border-slate-200 p-1.5 text-slate-950">
                          <span className="font-bold">{nc.equipamento}</span> <br />
                          <span className="text-[8px] text-slate-500 font-mono">{nc.norma}</span>
                        </td>
                        <td className="border border-slate-200 p-1.5 text-slate-600">
                          <p className="text-slate-900 font-medium mb-1">{nc.problema}</p>
                          <p className="text-slate-700 text-[8.5px] italic">Solução: {nc.recomendacao}</p>
                          <p className="text-slate-400 text-[8px] mt-0.5">Executor sugerido: {nc.responsavel}</p>
                        </td>
                        <td className="border border-slate-200 p-1.5 text-center">
                          <span className={`px-1.5 py-0.5 rounded text-[7.5px] font-bold ${
                            nc.prioridade === "IMEDIATO" ? "bg-red-100 text-red-800" :
                            nc.prioridade === "CURTO PRAZO" ? "bg-orange-100 text-orange-800" :
                            "bg-slate-100 text-slate-700"
                          }`}>
                            {nc.prioridade}
                          </span>
                        </td>
                        <td className="border border-slate-200 p-1.5 text-center font-semibold text-slate-900">{nc.prazo}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Block 8: Conclusao */}
            <div className="mb-6 page-break-inside-avoid">
              <h3 className="bg-slate-900 text-white text-xs font-bold uppercase px-2.5 py-1 rounded font-sans tracking-wider mb-3">
                8. CONCLUSÃO TÉCNICA E PARECER PERICIAL
              </h3>
              
              <div className="flex gap-4 items-start border border-slate-300 p-4 bg-slate-50 rounded mb-4">
                <div className={`p-2.5 rounded text-white font-bold text-sm shrink-0 uppercase tracking-wider ${
                  conclusao.status === "APROVADO" ? "bg-emerald-600" :
                  conclusao.status === "REPROVADO" ? "bg-red-600" : "bg-amber-600"
                }`}>
                  {conclusao.status}
                </div>
                <div>
                  <h4 className="text-xs font-bold text-slate-900 uppercase tracking-tight mb-1">Status de Avaliação do Playground</h4>
                  <p className="text-xs text-slate-700 leading-relaxed text-justify font-sans">{secoes["conclusao_text"]}</p>
                </div>
              </div>

              <div className="border border-slate-200 rounded p-4 bg-slate-50/50">
                <h4 className="text-xs font-bold text-slate-900 mb-2">Fundamentação de Engenharia Responsável</h4>
                <p className="text-xs text-slate-700 leading-relaxed text-justify italic">{conclusao.parecer}</p>
              </div>
            </div>

            {/* Signature Block */}
            <div className="mt-12 border-t border-slate-200 pt-6 flex justify-between items-end page-break-inside-avoid">
              <div className="text-slate-500 text-[10px] leading-tight pb-4">
                <p className="font-bold text-slate-800">VL Engenharia Diagnóstica</p>
                <p>Inspeção Técnica de Playgrounds NBR 16071</p>
                <p>Tel: (81) 98444-2592 / PE</p>
              </div>
              <div className="text-center w-60">
                <ReportSignature 
                  isBlank={laudoParams.blankSignature} 
                  engName="Vitor Leonardo Cordeiro Linhares" 
                  engCrea="CREA-PE: 1822299490" 
                  additionalRole="Engenheiro Mecânico Responsável"
                />
              </div>
            </div>
          </>
        )}
      </div>
        </div>
      </div>
    </div>
  );
}
